import { execSync, spawnSync } from 'node:child_process';
import { copyFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const SKILL_VERSION = '1.0.0';

export function assertPlaywrightInstalled(repoRoot) {
  try {
    execSync('npx playwright --version', {
      cwd: repoRoot,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
    });
  } catch {
    throw new Error(
      '@playwright/test is not available in this repo. Install dev deps:\n' +
        '  npm install -D @playwright/test\n' +
        '  npx playwright install chromium',
    );
  }
}

export function ensureCapturePlaywrightConfig(captureDir, assetsDir, baseURL, viewport) {
  const dest = join(captureDir, 'playwright.config.mjs');
  if (!existsSync(dest)) {
    copyFileSync(
      join(assetsDir, 'playwright.capture.config.mjs'),
      dest,
    );
  }
  return dest;
}

/**
 * Static page — Playwright CLI screenshot (no spec file).
 */
export function screenshotUrl(repoRoot, url, outPath, { fullPage = true, viewport } = {}) {
  mkdirSync(dirname(outPath), { recursive: true });
  const args = ['playwright', 'screenshot', url, outPath];
  if (fullPage) args.push('--full-page');
  if (viewport?.width && viewport?.height) {
    args.push('--viewport-size', `${viewport.width},${viewport.height}`);
  }
  const result = spawnSync('npx', args, {
    cwd: repoRoot,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  });
  if (result.status !== 0) {
    throw new Error(
      `playwright screenshot failed for ${url}:\n${result.stderr || result.stdout}`,
    );
  }
}

/**
 * Pages with actions — generated spec + playwright test.
 */
export function writeCaptureSpec(specPath, pages, baseURL) {
  const lines = [
    '// Generated by playwright-screenshots/scripts/capture.mjs — do not edit by hand',
    "import { test } from '@playwright/test';",
    '',
  ];
  for (const page of pages) {
    const safeName = page.id.replace(/[^a-zA-Z0-9-_]/g, '_');
    lines.push(`test('capture ${safeName}', async ({ page }) => {`);
    lines.push(`  await page.goto(${JSON.stringify(page.path)}, { waitUntil: 'networkidle' });`);
    for (const action of page.actions ?? []) {
      appendAction(lines, action);
    }
    const shotPath = page._outPath;
    lines.push(
      `  await page.screenshot({ path: ${JSON.stringify(shotPath)}, fullPage: ${Boolean(page.fullPage !== false)} });`,
    );
    lines.push('});');
    lines.push('');
  }
  mkdirSync(dirname(specPath), { recursive: true });
  writeFileSync(specPath, `${lines.join('\n')}\n`, 'utf8');
}

function appendAction(lines, action) {
  if (action.waitForSelector) {
    const timeout = action.timeoutMs ?? 10_000;
    lines.push(
      `  await page.locator(${JSON.stringify(action.waitForSelector)}).waitFor({ timeout: ${timeout} });`,
    );
  }
  if (action.click) {
    lines.push(`  await page.locator(${JSON.stringify(action.click)}).click();`);
  }
  if (action.fill) {
    for (const [selector, value] of Object.entries(action.fill)) {
      lines.push(`  await page.locator(${JSON.stringify(selector)}).fill(${JSON.stringify(value)});`);
    }
  }
  if (action.press) {
    lines.push(`  await page.keyboard.press(${JSON.stringify(action.press)});`);
  }
  if (action.waitMs) {
    lines.push(`  await page.waitForTimeout(${Number(action.waitMs)});`);
  }
}

export function runCaptureTests(repoRoot, captureDir, baseURL) {
  const env = { ...process.env, DOCS_CAPTURE_BASE_URL: baseURL };
  const result = spawnSync(
    'npx',
    ['playwright', 'test', 'run.capture.spec.mjs', '--config', join(captureDir, 'playwright.config.mjs')],
    {
      cwd: captureDir,
      encoding: 'utf8',
      env,
      stdio: ['ignore', 'pipe', 'pipe'],
    },
  );
  if (result.status !== 0) {
    throw new Error(`playwright test failed:\n${result.stderr || result.stdout}`);
  }
}

export function stampManifest(manifest) {
  manifest.generatedBy = 'playwright-screenshots';
  manifest.version = SKILL_VERSION;
  manifest.generatedAt = new Date().toISOString();
  return manifest;
}

export function skillAssetsDir() {
  const here = dirname(fileURLToPath(import.meta.url));
  return join(here, '..', '..', 'assets');
}
